# Generated by Django 5.2.7 on 2025-10-26 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
